version: '3.2'

services:
  nginx:
    image: nginx:1.12.2
    ports:
      - "4000:80"
    volumes:
      - .:/application/code:rw
      - ./nginx-symfony.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build: .
    volumes: 
      - .:/application/code:rw
    links:
      - database
  database:
    image: postgres:10.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes: 
      - ./database:/var/lib/postgresql/data
  pgadmin:
    image: thajeztah/pgadmin4
    ports:
      - "5050:5050"
    links:
      - database

